<?php
/**
 * Card
 *
 * PHP version 5
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Netpay API
 *
 * Netpay API for Cash and Credit Card
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Netpay\Client\Model;

use \ArrayAccess;
use \Netpay\Client\ObjectSerializer;

/**
 * Card Class Doc Comment
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Card implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Card';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'token' => 'string',
'exp_year' => 'string',
'exp_month' => 'string',
'last_four_digits' => 'string',
'card_holder_name' => 'string',
'brand' => 'string',
'device_finger_print' => 'string',
'ip_address' => 'string',
'bank' => 'string',
'type' => 'string',
'country' => 'string',
'scheme' => 'string',
'card_prefix' => 'string',
'pre_auth' => 'bool',
'vault' => 'bool',
'simple_use' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'token' => null,
'exp_year' => null,
'exp_month' => null,
'last_four_digits' => null,
'card_holder_name' => null,
'brand' => null,
'device_finger_print' => null,
'ip_address' => null,
'bank' => null,
'type' => null,
'country' => null,
'scheme' => null,
'card_prefix' => null,
'pre_auth' => null,
'vault' => null,
'simple_use' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'token' => 'token',
'exp_year' => 'expYear',
'exp_month' => 'expMonth',
'last_four_digits' => 'lastFourDigits',
'card_holder_name' => 'cardHolderName',
'brand' => 'brand',
'device_finger_print' => 'deviceFingerPrint',
'ip_address' => 'ipAddress',
'bank' => 'bank',
'type' => 'type',
'country' => 'country',
'scheme' => 'scheme',
'card_prefix' => 'cardPrefix',
'pre_auth' => 'preAuth',
'vault' => 'vault',
'simple_use' => 'simpleUse'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'token' => 'setToken',
'exp_year' => 'setExpYear',
'exp_month' => 'setExpMonth',
'last_four_digits' => 'setLastFourDigits',
'card_holder_name' => 'setCardHolderName',
'brand' => 'setBrand',
'device_finger_print' => 'setDeviceFingerPrint',
'ip_address' => 'setIpAddress',
'bank' => 'setBank',
'type' => 'setType',
'country' => 'setCountry',
'scheme' => 'setScheme',
'card_prefix' => 'setCardPrefix',
'pre_auth' => 'setPreAuth',
'vault' => 'setVault',
'simple_use' => 'setSimpleUse'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'token' => 'getToken',
'exp_year' => 'getExpYear',
'exp_month' => 'getExpMonth',
'last_four_digits' => 'getLastFourDigits',
'card_holder_name' => 'getCardHolderName',
'brand' => 'getBrand',
'device_finger_print' => 'getDeviceFingerPrint',
'ip_address' => 'getIpAddress',
'bank' => 'getBank',
'type' => 'getType',
'country' => 'getCountry',
'scheme' => 'getScheme',
'card_prefix' => 'getCardPrefix',
'pre_auth' => 'getPreAuth',
'vault' => 'getVault',
'simple_use' => 'getSimpleUse'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['token'] = isset($data['token']) ? $data['token'] : null;
        $this->container['exp_year'] = isset($data['exp_year']) ? $data['exp_year'] : null;
        $this->container['exp_month'] = isset($data['exp_month']) ? $data['exp_month'] : null;
        $this->container['last_four_digits'] = isset($data['last_four_digits']) ? $data['last_four_digits'] : null;
        $this->container['card_holder_name'] = isset($data['card_holder_name']) ? $data['card_holder_name'] : null;
        $this->container['brand'] = isset($data['brand']) ? $data['brand'] : null;
        $this->container['device_finger_print'] = isset($data['device_finger_print']) ? $data['device_finger_print'] : null;
        $this->container['ip_address'] = isset($data['ip_address']) ? $data['ip_address'] : null;
        $this->container['bank'] = isset($data['bank']) ? $data['bank'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['scheme'] = isset($data['scheme']) ? $data['scheme'] : null;
        $this->container['card_prefix'] = isset($data['card_prefix']) ? $data['card_prefix'] : null;
        $this->container['pre_auth'] = isset($data['pre_auth']) ? $data['pre_auth'] : null;
        $this->container['vault'] = isset($data['vault']) ? $data['vault'] : null;
        $this->container['simple_use'] = isset($data['simple_use']) ? $data['simple_use'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string $token token
     *
     * @return $this
     */
    public function setToken($token)
    {
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets exp_year
     *
     * @return string
     */
    public function getExpYear()
    {
        return $this->container['exp_year'];
    }

    /**
     * Sets exp_year
     *
     * @param string $exp_year exp_year
     *
     * @return $this
     */
    public function setExpYear($exp_year)
    {
        $this->container['exp_year'] = $exp_year;

        return $this;
    }

    /**
     * Gets exp_month
     *
     * @return string
     */
    public function getExpMonth()
    {
        return $this->container['exp_month'];
    }

    /**
     * Sets exp_month
     *
     * @param string $exp_month exp_month
     *
     * @return $this
     */
    public function setExpMonth($exp_month)
    {
        $this->container['exp_month'] = $exp_month;

        return $this;
    }

    /**
     * Gets last_four_digits
     *
     * @return string
     */
    public function getLastFourDigits()
    {
        return $this->container['last_four_digits'];
    }

    /**
     * Sets last_four_digits
     *
     * @param string $last_four_digits last_four_digits
     *
     * @return $this
     */
    public function setLastFourDigits($last_four_digits)
    {
        $this->container['last_four_digits'] = $last_four_digits;

        return $this;
    }

    /**
     * Gets card_holder_name
     *
     * @return string
     */
    public function getCardHolderName()
    {
        return $this->container['card_holder_name'];
    }

    /**
     * Sets card_holder_name
     *
     * @param string $card_holder_name card_holder_name
     *
     * @return $this
     */
    public function setCardHolderName($card_holder_name)
    {
        $this->container['card_holder_name'] = $card_holder_name;

        return $this;
    }

    /**
     * Gets brand
     *
     * @return string
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param string $brand brand
     *
     * @return $this
     */
    public function setBrand($brand)
    {
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets device_finger_print
     *
     * @return string
     */
    public function getDeviceFingerPrint()
    {
        return $this->container['device_finger_print'];
    }

    /**
     * Sets device_finger_print
     *
     * @param string $device_finger_print device_finger_print
     *
     * @return $this
     */
    public function setDeviceFingerPrint($device_finger_print)
    {
        $this->container['device_finger_print'] = $device_finger_print;

        return $this;
    }

    /**
     * Gets ip_address
     *
     * @return string
     */
    public function getIpAddress()
    {
        return $this->container['ip_address'];
    }

    /**
     * Sets ip_address
     *
     * @param string $ip_address ip_address
     *
     * @return $this
     */
    public function setIpAddress($ip_address)
    {
        $this->container['ip_address'] = $ip_address;

        return $this;
    }

    /**
     * Gets bank
     *
     * @return string
     */
    public function getBank()
    {
        return $this->container['bank'];
    }

    /**
     * Sets bank
     *
     * @param string $bank bank
     *
     * @return $this
     */
    public function setBank($bank)
    {
        $this->container['bank'] = $bank;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets scheme
     *
     * @return string
     */
    public function getScheme()
    {
        return $this->container['scheme'];
    }

    /**
     * Sets scheme
     *
     * @param string $scheme scheme
     *
     * @return $this
     */
    public function setScheme($scheme)
    {
        $this->container['scheme'] = $scheme;

        return $this;
    }

    /**
     * Gets card_prefix
     *
     * @return string
     */
    public function getCardPrefix()
    {
        return $this->container['card_prefix'];
    }

    /**
     * Sets card_prefix
     *
     * @param string $card_prefix card_prefix
     *
     * @return $this
     */
    public function setCardPrefix($card_prefix)
    {
        $this->container['card_prefix'] = $card_prefix;

        return $this;
    }

    /**
     * Gets pre_auth
     *
     * @return bool
     */
    public function getPreAuth()
    {
        return $this->container['pre_auth'];
    }

    /**
     * Sets pre_auth
     *
     * @param bool $pre_auth pre_auth
     *
     * @return $this
     */
    public function setPreAuth($pre_auth)
    {
        $this->container['pre_auth'] = $pre_auth;

        return $this;
    }

    /**
     * Gets vault
     *
     * @return bool
     */
    public function getVault()
    {
        return $this->container['vault'];
    }

    /**
     * Sets vault
     *
     * @param bool $vault vault
     *
     * @return $this
     */
    public function setVault($vault)
    {
        $this->container['vault'] = $vault;

        return $this;
    }

    /**
     * Gets simple_use
     *
     * @return bool
     */
    public function getSimpleUse()
    {
        return $this->container['simple_use'];
    }

    /**
     * Sets simple_use
     *
     * @param bool $simple_use simple_use
     *
     * @return $this
     */
    public function setSimpleUse($simple_use)
    {
        $this->container['simple_use'] = $simple_use;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
