<?php
/**
 * Charges
 *
 * PHP version 5
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Netpay API
 *
 * Netpay API for Cash and Credit Card
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Netpay\Client\Model;

use \ArrayAccess;
use \Netpay\Client\ObjectSerializer;

/**
 * Charges Class Doc Comment
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Charges implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Charges';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'amount' => 'float',
'source' => 'string',
'description' => 'string',
'payment_method' => 'string',
'currency' => 'string',
'installments' => '\Netpay\Client\Model\Installments',
'billing' => '\Netpay\Client\Model\Billing',
'ship' => '\Netpay\Client\Model\Ship',
'redirect3ds_uri' => 'string',
'client' => '\Netpay\Client\Model\Client',
'cvv' => 'string',
'save_card' => 'bool',
'deviceInformation' => '\Netpay\Client\Model\DeviceInformationCharges',
        'zoneAware' => 'object',
        'deviceFingerPrint' => 'string',
        'sessionId' => 'string',
'instegrationsdk' => 'string',
'integrationSdkVersion' => 'string',
'referenceID' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'amount' => 'float',
'source' => null,
'description' => null,
'payment_method' => null,
'currency' => null,
'installments' => null,
'billing' => null,
'ship' => null,
'redirect3ds_uri' => null,
'client' => null,
'cvv' => null,
'save_card' => null,
'deviceInformation' => null,
        'zoneAware' => null,
        'deviceFingerPrint' => null,
        'sessionId' => null,
'instegrationsdk' => null,
'integrationSdkVersion' => null,
'referenceID' => null];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amount' => 'amount',
'source' => 'source',
'description' => 'description',
'payment_method' => 'paymentMethod',
'currency' => 'currency',
'installments' => 'installments',
'billing' => 'billing',
'ship' => 'ship',
'redirect3ds_uri' => 'redirect3dsUri',
'client' => 'client',
'cvv' => 'cvv',
'save_card' => 'saveCard',
'deviceInformation' => 'deviceInformation',
        'zoneAware' => 'zoneAware',
        'deviceFingerPrint' => 'deviceFingerPrint',
        'sessionId' => 'sessionId',
'instegrationsdk' => 'instegrationsdk',
'integrationSdkVersion' => 'integrationSdkVersion',
'referenceID' => 'referenceID'   ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amount' => 'setAmount',
'source' => 'setSource',
'description' => 'setDescription',
'payment_method' => 'setPaymentMethod',
'currency' => 'setCurrency',
'installments' => 'setInstallments',
'billing' => 'setBilling',
'ship' => 'setShip',
'redirect3ds_uri' => 'setRedirect3dsUri',
'client' => 'setClient',
'cvv' => 'setCvv',
'save_card' => 'setSaveCard',
'deviceInformation' => 'setDeviceInformation',
        'zoneAware' => 'setZoneAware',
        'deviceFingerPrint' => 'setDeviceFingerPrint',
        'sessionId' => 'setSessionId',
'instegrationsdk' => 'setInstegrationsdk',
'integrationSdkVersion' => 'setIntegrationSdkVersion',
'referenceID' => 'setReferenceId'];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amount' => 'getAmount',
'source' => 'getSource',
'description' => 'getDescription',
'payment_method' => 'getPaymentMethod',
'currency' => 'getCurrency',
'installments' => 'getInstallments',
'billing' => 'getBilling',
'ship' => 'getShip',
'redirect3ds_uri' => 'getRedirect3dsUri',
'client' => 'getClient',
'cvv' => 'getCvv',
'save_card' => 'getSaveCard',
'deviceInformation' => 'getDeviceInformation',
        'zoneAware' => 'getZoneAware',
        'deviceFingerPrint' => 'getDeviceFingerPrint',
        'sessionId' => 'getSessionId',
'instegrationsdk' => 'getInstegrationsdk',
'integrationSdkVersion' => 'getIntegrationSdkVersion',
'referenceID' => 'getReferenceId'];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['source'] = isset($data['source']) ? $data['source'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['payment_method'] = isset($data['payment_method']) ? $data['payment_method'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['installments'] = isset($data['installments']) ? $data['installments'] : null;
        $this->container['billing'] = isset($data['billing']) ? $data['billing'] : null;
        $this->container['ship'] = isset($data['ship']) ? $data['ship'] : null;
        $this->container['redirect3ds_uri'] = isset($data['redirect3ds_uri']) ? $data['redirect3ds_uri'] : null;
        $this->container['client'] = isset($data['client']) ? $data['client'] : null;
        $this->container['cvv'] = isset($data['cvv']) ? $data['cvv'] : null;
        $this->container['save_card'] = isset($data['save_card']) ? $data['save_card'] : null;
        $this->container['deviceInformation'] = isset($data['deviceInformation']) ? $data['deviceInformation'] : null;
        $this->container['zoneAware'] = isset($data['zoneAware']) ? $data['zoneAware'] : null;
        $this->container['deviceFingerPrint'] = isset($data['deviceFingerPrint']) ? $data['deviceFingerPrint'] : null;
        $this->container['sessionId'] = isset($data['sessionId']) ? $data['sessionId'] : null;
        $this->container['instegrationsdk'] = isset($data['instegrationsdk']) ? $data['instegrationsdk'] : null;
        $this->container['integrationSdkVersion'] = isset($data['integrationSdkVersion']) ? $data['integrationSdkVersion'] : null;
        $this->container['referenceID'] = isset($data['referenceID']) ? $data['referenceID'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['source'] === null) {
            $invalidProperties[] = "'source' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['payment_method'] === null) {
            $invalidProperties[] = "'payment_method' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ($this->container['billing'] === null) {
            $invalidProperties[] = "'billing' can't be null";
        }
        if ($this->container['deviceInformation'] === null) {
            $invalidProperties[] = "'deviceInformation' can't be null";
        }
        if ($this->container['instegrationsdk'] === null) {
            $invalidProperties[] = "'instegrationsdk' can't be null";
        }
        if ($this->container['integrationSdkVersion'] === null) {
            $invalidProperties[] = "'integrationSdkVersion' can't be null";
        }
        if ($this->container['referenceID'] === null) {
            $invalidProperties[] = "'referenceID' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float $amount amount
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets referenceID
     *
     * @return string
     */
    public function getReferenceId()
    {
        return $this->container['referenceID'];
    }

    /**
     * Sets deviceInformation
     *
     * @param string $deviceInformation deviceInformation
     *
     * @return $this
     */
    public function setDeviceInformation($deviceInformation)
    {
        $this->container['deviceInformation'] = $deviceInformation;

        return $this;
    }

        /**
     * Gets deviceInformation
     *
     * @return string
     */
    public function getDeviceInformation()
    {
        return $this->container['deviceInformation'];
    }

        /**
     * Gets instegrationsdk
     *
     * @return string
     */
    public function getInstegrationsdk()
    {
        return $this->container['instegrationsdk'];
    }

    /**
     * Sets instegrationsdk
     *
     * @param string $instegrationsdk instegrationsdk
     *
     * @return $this
     */
    public function setInstegrationsdk($instegrationsdk)
    {
        $this->container['instegrationsdk'] = $instegrationsdk;

        return $this;
    }

    /**
     * Gets integrationSdkVersion
     *
     * @return string
     */
    public function getIntegrationSdkVersion()
    {
        return $this->container['integrationSdkVersion'];
    }

    /**
     * Sets integrationSdkVersion
     *
     * @param string $integrationSdkVersion integrationSdkVersion
     *
     * @return $this
     */
    public function setIntegrationSdkVersion($integrationSdkVersion)
    {
        $this->container['integrationSdkVersion'] = $integrationSdkVersion;

        return $this;
    }

    /**
     * Sets referenceID
     *
     * @param string $referenceID referenceID
     *
     * @return $this
     */
    public function setReferenceId($referenceID)
    {
        $this->container['referenceID'] = $referenceID;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string $source source
     *
     * @return $this
     */
    public function setSource($source)
    {
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return string
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param string $payment_method payment_method
     *
     * @return $this
     */
    public function setPaymentMethod($payment_method)
    {
        $this->container['payment_method'] = $payment_method;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency currency
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets installments
     *
     * @return \Netpay\Client\Model\Installments
     */
    public function getInstallments()
    {
        return $this->container['installments'];
    }

    /**
     * Sets installments
     *
     * @param \Netpay\Client\Model\Installments $installments installments
     *
     * @return $this
     */
    public function setInstallments($installments)
    {
        $this->container['installments'] = $installments;

        return $this;
    }

    /**
     * Gets billing
     *
     * @return \Netpay\Client\Model\Billing
     */
    public function getBilling()
    {
        return $this->container['billing'];
    }

    /**
     * Sets billing
     *
     * @param \Netpay\Client\Model\Billing $billing billing
     *
     * @return $this
     */
    public function setBilling($billing)
    {
        $this->container['billing'] = $billing;

        return $this;
    }

    /**
     * Gets ship
     *
     * @return \Netpay\Client\Model\Ship
     */
    public function getShip()
    {
        return $this->container['ship'];
    }

    /**
     * Sets ship
     *
     * @param \Netpay\Client\Model\Ship $ship ship
     *
     * @return $this
     */
    public function setShip($ship)
    {
        $this->container['ship'] = $ship;

        return $this;
    }

    /**
     * Gets redirect3ds_uri
     *
     * @return string
     */
    public function getRedirect3dsUri()
    {
        return $this->container['redirect3ds_uri'];
    }

    /**
     * Sets redirect3ds_uri
     *
     * @param string $redirect3ds_uri redirect3ds_uri
     *
     * @return $this
     */
    public function setRedirect3dsUri($redirect3ds_uri)
    {
        $this->container['redirect3ds_uri'] = $redirect3ds_uri;

        return $this;
    }

    /**
     * Gets client
     *
     * @return \Netpay\Client\Model\Client
     */
    public function getClient()
    {
        return $this->container['client'];
    }

    /**
     * Sets client
     *
     * @param \Netpay\Client\Model\Client $client client
     *
     * @return $this
     */
    public function setClient($client)
    {
        $this->container['client'] = $client;

        return $this;
    }

    /**
     * Gets cvv
     *
     * @return string
     */
    public function getCvv()
    {
        return $this->container['cvv'];
    }

    /**
     * Sets cvv
     *
     * @param string $cvv cvv
     *
     * @return $this
     */
    public function setCvv($cvv)
    {
        $this->container['cvv'] = $cvv;

        return $this;
    }

    /**
     * Gets save_card
     *
     * @return bool
     */
    public function getSaveCard()
    {
        return $this->container['save_card'];
    }

    /**
     * Sets save_card
     *
     * @param bool $save_card save_card
     *
     * @return $this
     */
    public function setSaveCard($save_card)
    {
        $this->container['save_card'] = $save_card;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets zoneAware
     *
     * @return object
     */
    public function getZoneAware()
    {
        return $this->container['zoneAware'];
    }

    /**
     * Sets zoneAware
     *
     * @param object $zoneAware Anti-fraud signals (e.g. clientIPAdress)
     *
     * @return $this
     */
    public function setZoneAware($zoneAware)
    {
        $this->container['zoneAware'] = $zoneAware;

        return $this;
    }

    /**
     * Gets deviceFingerPrint
     *
     * @return string
     */
    public function getDeviceFingerPrint()
    {
        return $this->container['deviceFingerPrint'];
    }

    /**
     * Sets deviceFingerPrint
     *
     * @param string $deviceFingerPrint Anti-fraud device fingerprint (ThreatMetrix session id)
     *
     * @return $this
     */
    public function setDeviceFingerPrint($deviceFingerPrint)
    {
        $this->container['deviceFingerPrint'] = $deviceFingerPrint;

        return $this;
    }

    /**
     * Gets sessionId
     *
     * @return string
     */
    public function getSessionId()
    {
        return $this->container['sessionId'];
    }

    /**
     * Sets sessionId
     *
     * @param string $sessionId Anti-fraud device fingerprint session id
     *
     * @return $this
     */
    public function setSessionId($sessionId)
    {
        $this->container['sessionId'] = $sessionId;

        return $this;
    }

}
