<?php
/**
 * ChargesResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Netpay API
 *
 * Netpay API for Cash and Credit Card
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Netpay\Client\Model;

use \ArrayAccess;
use \Netpay\Client\ObjectSerializer;

/**
 * ChargesResponse Class Doc Comment
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChargesResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ChargesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'amount' => 'float',
'source' => 'string',
'description' => 'string',
'status' => 'string',
'transaction_token_id' => 'string',
'redirect3ds_uri' => 'string',
'return_url' => 'string',
'payment_method' => 'string',
'currency' => 'string',
'created_at' => 'string',
'error' => 'string',
'installments' => '\Netpay\Client\Model\AllOfChargesResponseInstallments',
'ship' => '\Netpay\Client\Model\AllOfChargesResponseShip',
'client' => '\Netpay\Client\Model\AllOfChargesResponseClient',
'save_card' => 'bool',
'instegrationsdk' => 'string',
'integration_sdk_version' => 'string',
'cvv' => 'string',
'merchant_ref_code' => 'string',
'token_request_dto' => 'string',
'seamless' => 'bool',
'payment_source' => '\Netpay\Client\Model\PaymentSource',
'billing' => '\Netpay\Client\Model\Billing',
'three_d_secure' => '\Netpay\Client\Model\threeDSecureResponse',
'referenceID' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'amount' => 'float',
'source' => null,
'description' => null,
'status' => null,
'transaction_token_id' => null,
'redirect3ds_uri' => null,
'return_url' => null,
'payment_method' => null,
'currency' => null,
'created_at' => null,
'error' => null,
'installments' => null,
'ship' => null,
'client' => null,
'save_card' => null,
'instegrationsdk' => null,
'integration_sdk_version' => null,
'cvv' => null,
'merchant_ref_code' => null,
'token_request_dto' => null,
'seamless' => null,
'payment_source' => null,
'billing' => null,
'three_d_secure' => null,
'referenceID' => null   
 ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amount' => 'amount',
'source' => 'source',
'description' => 'description',
'status' => 'status',
'transaction_token_id' => 'transactionTokenId',
'redirect3ds_uri' => 'redirect3dsUri',
'return_url' => 'returnUrl',
'payment_method' => 'paymentMethod',
'currency' => 'currency',
'created_at' => 'createdAt',
'error' => 'error',
'installments' => 'installments',
'ship' => 'ship',
'client' => 'client',
'save_card' => 'saveCard',
'instegrationsdk' => 'instegrationsdk',
'integration_sdk_version' => 'integrationSdkVersion',
'cvv' => 'cvv',
'merchant_ref_code' => 'merchantRefCode',
'token_request_dto' => 'tokenRequestDTO',
'seamless' => 'seamless',
'payment_source' => 'paymentSource',
'billing' => 'billing',
'three_d_secure' => 'threeDSecureResponse',
'referenceID' => 'referenceID'

];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amount' => 'setAmount',
'source' => 'setSource',
'description' => 'setDescription',
'status' => 'setStatus',
'transaction_token_id' => 'setTransactionTokenId',
'redirect3ds_uri' => 'setRedirect3dsUri',
'return_url' => 'setReturnUrl',
'payment_method' => 'setPaymentMethod',
'currency' => 'setCurrency',
'created_at' => 'setCreatedAt',
'error' => 'setError',
'installments' => 'setInstallments',
'ship' => 'setShip',
'client' => 'setClient',
'save_card' => 'setSaveCard',
'instegrationsdk' => 'setInstegrationsdk',
'integration_sdk_version' => 'setIntegrationSdkVersion',
'cvv' => 'setCvv',
'merchant_ref_code' => 'setMerchantRefCode',
'token_request_dto' => 'setTokenRequestDto',
'seamless' => 'setSeamless',
'payment_source' => 'setPaymentSource',
'billing' => 'setBilling',
'three_d_secure' => 'setThreeDSecureResponse',
'referenceID' => 'setReferenceId'

];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amount' => 'getAmount',
'source' => 'getSource',
'description' => 'getDescription',
'status' => 'getStatus',
'transaction_token_id' => 'getTransactionTokenId',
'redirect3ds_uri' => 'getRedirect3dsUri',
'return_url' => 'getReturnUrl',
'payment_method' => 'getPaymentMethod',
'currency' => 'getCurrency',
'created_at' => 'getCreatedAt',
'error' => 'getError',
'installments' => 'getInstallments',
'ship' => 'getShip',
'client' => 'getClient',
'save_card' => 'getSaveCard',
'instegrationsdk' => 'getInstegrationsdk',
'integration_sdk_version' => 'getIntegrationSdkVersion',
'cvv' => 'getCvv',
'merchant_ref_code' => 'getMerchantRefCode',
'token_request_dto' => 'getTokenRequestDto',
'seamless' => 'getSeamless',
'payment_source' => 'getPaymentSource',
'billing' => 'getBilling',
'transaction_dto' => 'getTransactionDto',
'three_d_secure' => 'getThreeDSecureResponse',
'referenceID' => 'getReferenceId'

];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['source'] = isset($data['source']) ? $data['source'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['transaction_token_id'] = isset($data['transaction_token_id']) ? $data['transaction_token_id'] : null;
        $this->container['redirect3ds_uri'] = isset($data['redirect3ds_uri']) ? $data['redirect3ds_uri'] : null;
        $this->container['return_url'] = isset($data['return_url']) ? $data['return_url'] : null;
        $this->container['payment_method'] = isset($data['payment_method']) ? $data['payment_method'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['error'] = isset($data['error']) ? $data['error'] : null;
        $this->container['installments'] = isset($data['installments']) ? $data['installments'] : null;
        $this->container['ship'] = isset($data['ship']) ? $data['ship'] : null;
        $this->container['client'] = isset($data['client']) ? $data['client'] : null;
        $this->container['save_card'] = isset($data['save_card']) ? $data['save_card'] : null;
        $this->container['instegrationsdk'] = isset($data['instegrationsdk']) ? $data['instegrationsdk'] : null;
        $this->container['integration_sdk_version'] = isset($data['integration_sdk_version']) ? $data['integration_sdk_version'] : null;
        $this->container['cvv'] = isset($data['cvv']) ? $data['cvv'] : null;
        $this->container['merchant_ref_code'] = isset($data['merchant_ref_code']) ? $data['merchant_ref_code'] : null;
        $this->container['token_request_dto'] = isset($data['token_request_dto']) ? $data['token_request_dto'] : null;
        $this->container['seamless'] = isset($data['seamless']) ? $data['seamless'] : null;
        $this->container['payment_source'] = isset($data['payment_source']) ? $data['payment_source'] : null;
        $this->container['billing'] = isset($data['billing']) ? $data['billing'] : null;
        $this->container['transaction_dto'] = isset($data['transaction_dto']) ? $data['transaction_dto'] : null;
        $this->container['three_d_secure'] = isset($data['three_d_secure']) ? $data['three_d_secure'] : null;
        $this->container['referenceID'] = isset($data['referenceID']) ? $data['referenceID'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float $amount amount
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string $source source
     *
     * @return $this
     */
    public function setSource($source)
    {
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets transaction_token_id
     *
     * @return string
     */
    public function getTransactionTokenId()
    {
        return $this->container['transaction_token_id'];
    }

    /**
     * Sets transaction_token_id
     *
     * @param string $transaction_token_id transaction_token_id
     *
     * @return $this
     */
    public function setTransactionTokenId($transaction_token_id)
    {
        $this->container['transaction_token_id'] = $transaction_token_id;

        return $this;
    }

    /**
     * Gets redirect3ds_uri
     *
     * @return string
     */
    public function getRedirect3dsUri()
    {
        return $this->container['redirect3ds_uri'];
    }

    /**
     * Sets redirect3ds_uri
     *
     * @param string $redirect3ds_uri redirect3ds_uri
     *
     * @return $this
     */
    public function setRedirect3dsUri($redirect3ds_uri)
    {
        $this->container['redirect3ds_uri'] = $redirect3ds_uri;

        return $this;
    }

    /**
     * Gets return_url
     *
     * @return string
     */
    public function getReturnUrl()
    {
        return $this->container['return_url'];
    }

    /**
     * Sets return_url
     *
     * @param string $return_url return_url
     *
     * @return $this
     */
    public function setReturnUrl($return_url)
    {
        $this->container['return_url'] = $return_url;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return string
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param string $payment_method payment_method
     *
     * @return $this
     */
    public function setPaymentMethod($payment_method)
    {
        $this->container['payment_method'] = $payment_method;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency currency
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at created_at
     *
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets error
     *
     * @return string
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param string $error error
     *
     * @return $this
     */
    public function setError($error)
    {
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets installments
     *
     * @return AllOfChargesResponseInstallments
     */
    public function getInstallments()
    {
        return $this->container['installments'];
    }

    /**
     * Sets installments
     *
     * @param AllOfChargesResponseInstallments $installments installments
     *
     * @return $this
     */
    public function setInstallments($installments)
    {
        $this->container['installments'] = $installments;

        return $this;
    }

        /**
     * Gets transaction_dto
     *
     * @return \Netpay\Client\Model\TransactionDTO
     */
    public function getTransactionDto()
    {
        return $this->container['transaction_dto'];
    }

    /**
     * Sets transaction_dto
     *
     * @param \Netpay\Client\Model\TransactionDTO $transaction_dto transaction_dto
     *
     * @return $this
     */
    public function setTransactionDto($transaction_dto)
    {
        $this->container['transaction_dto'] = $transaction_dto;

        return $this;
    }

    /**
     * Gets three_d_secure
     *
     * @return \Netpay\Client\Model\threeDSecureResponse
     */
    public function getThreeDSecureResponse()
    {
        return $this->container['three_d_secure'];
    }

    /**
     * Sets three_d_secure
     *
     * @param \Netpay\Client\Model\threeDSecureResponse $three_d_secure three_d_secure
     *
     * @return $this
     */
    public function setThreeDSecureResponse($three_d_secure)
    {
        $this->container['three_d_secure'] = $three_d_secure;

        return $this;
    }

     /**
     * Gets referenceID
     *
     * @return string
     */
    public function getReferenceId()
    {
        return $this->container['referenceID'];
    }

    /**
     * Sets referenceID
     *
     * @param string $referenceID referenceID
     *
     * @return $this
     */
    public function setReferenceId($referenceID)
    {
        $this->container['referenceID'] = $referenceID;

        return $this;
    }

    /**
     * Gets ship
     *
     * @return AllOfChargesResponseShip
     */
    public function getShip()
    {
        return $this->container['ship'];
    }

    /**
     * Sets ship
     *
     * @param AllOfChargesResponseShip $ship ship
     *
     * @return $this
     */
    public function setShip($ship)
    {
        $this->container['ship'] = $ship;

        return $this;
    }

    /**
     * Gets client
     *
     * @return AllOfChargesResponseClient
     */
    public function getClient()
    {
        return $this->container['client'];
    }

    /**
     * Sets client
     *
     * @param AllOfChargesResponseClient $client client
     *
     * @return $this
     */
    public function setClient($client)
    {
        $this->container['client'] = $client;

        return $this;
    }

    /**
     * Gets save_card
     *
     * @return bool
     */
    public function getSaveCard()
    {
        return $this->container['save_card'];
    }

    /**
     * Sets save_card
     *
     * @param bool $save_card save_card
     *
     * @return $this
     */
    public function setSaveCard($save_card)
    {
        $this->container['save_card'] = $save_card;

        return $this;
    }

    /**
     * Gets instegrationsdk
     *
     * @return string
     */
    public function getInstegrationsdk()
    {
        return $this->container['instegrationsdk'];
    }

    /**
     * Sets instegrationsdk
     *
     * @param string $instegrationsdk instegrationsdk
     *
     * @return $this
     */
    public function setInstegrationsdk($instegrationsdk)
    {
        $this->container['instegrationsdk'] = $instegrationsdk;

        return $this;
    }

    /**
     * Gets integration_sdk_version
     *
     * @return string
     */
    public function getIntegrationSdkVersion()
    {
        return $this->container['integration_sdk_version'];
    }

    /**
     * Sets integration_sdk_version
     *
     * @param string $integration_sdk_version integration_sdk_version
     *
     * @return $this
     */
    public function setIntegrationSdkVersion($integration_sdk_version)
    {
        $this->container['integration_sdk_version'] = $integration_sdk_version;

        return $this;
    }

    /**
     * Gets cvv
     *
     * @return string
     */
    public function getCvv()
    {
        return $this->container['cvv'];
    }

    /**
     * Sets cvv
     *
     * @param string $cvv cvv
     *
     * @return $this
     */
    public function setCvv($cvv)
    {
        $this->container['cvv'] = $cvv;

        return $this;
    }

    /**
     * Gets merchant_ref_code
     *
     * @return string
     */
    public function getMerchantRefCode()
    {
        return $this->container['merchant_ref_code'];
    }

    /**
     * Sets merchant_ref_code
     *
     * @param string $merchant_ref_code merchant_ref_code
     *
     * @return $this
     */
    public function setMerchantRefCode($merchant_ref_code)
    {
        $this->container['merchant_ref_code'] = $merchant_ref_code;

        return $this;
    }

    /**
     * Gets token_request_dto
     *
     * @return string
     */
    public function getTokenRequestDto()
    {
        return $this->container['token_request_dto'];
    }

    /**
     * Sets token_request_dto
     *
     * @param string $token_request_dto token_request_dto
     *
     * @return $this
     */
    public function setTokenRequestDto($token_request_dto)
    {
        $this->container['token_request_dto'] = $token_request_dto;

        return $this;
    }

    /**
     * Gets seamless
     *
     * @return bool
     */
    public function getSeamless()
    {
        return $this->container['seamless'];
    }

    /**
     * Sets seamless
     *
     * @param bool $seamless seamless
     *
     * @return $this
     */
    public function setSeamless($seamless)
    {
        $this->container['seamless'] = $seamless;

        return $this;
    }

    /**
     * Gets payment_source
     *
     * @return \Netpay\Client\Model\PaymentSource
     */
    public function getPaymentSource()
    {
        return $this->container['payment_source'];
    }

    /**
     * Sets payment_source
     *
     * @param \Netpay\Client\Model\PaymentSource $payment_source payment_source
     *
     * @return $this
     */
    public function setPaymentSource($payment_source)
    {
        $this->container['payment_source'] = $payment_source;

        return $this;
    }

    /**
     * Gets billing
     *
     * @return \Netpay\Client\Model\Billing
     */
    public function getBilling()
    {
        return $this->container['billing'];
    }

    /**
     * Sets billing
     *
     * @param \Netpay\Client\Model\Billing $billing billing
     *
     * @return $this
     */
    public function setBilling($billing)
    {
        $this->container['billing'] = $billing;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
