<?php
/**
 * ConfigResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Netpay API
 *
 * Netpay API for Cash and Credit Card
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Netpay\Client\Model;

use \ArrayAccess;
use \Netpay\Client\ObjectSerializer;

/**
 * ConfigResponse Class Doc Comment
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConfigResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ConfigResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'store_id_adq' => 'int',
'private_key' => 'string',
'status' => '\Netpay\Client\Model\ConfigResponseStatus',
'mid' => 'string',
'organization_id' => 'string',
'web_authorizer_url' => 'string',
'merchant_web_hook' => 'string',
'created_date' => 'string',
'updated_date' => 'string',
'cash_payment_enable' => 'string',
'day_payment_expire' => 'int',
'brand_card_allow' => 'string',
'promotion_enable' => 'string',
'promotion_allow' => 'string',
'credit_card_enable' => 'string',
'debit_card_enable' => 'string',
'image_header' => 'string',
'image_name' => 'string',
'color_header' => 'string',
'color_button' => 'string',
'promotion_amount03' => 'string',
'promotion_amount06' => 'string',
'promotion_amount09' => 'string',
'promotion_amount12' => 'string',
'promotion_amount18' => 'string',
'oxxo_pay' => '\Netpay\Client\Model\OxxoPayConfig',
'active' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'store_id_adq' => null,
'private_key' => null,
'status' => null,
'mid' => null,
'organization_id' => null,
'web_authorizer_url' => null,
'merchant_web_hook' => null,
'created_date' => null,
'updated_date' => null,
'cash_payment_enable' => null,
'day_payment_expire' => null,
'brand_card_allow' => null,
'promotion_enable' => null,
'promotion_allow' => null,
'credit_card_enable' => null,
'debit_card_enable' => null,
'image_header' => null,
'image_name' => null,
'color_header' => null,
'color_button' => null,
'promotion_amount03' => null,
'promotion_amount06' => null,
'promotion_amount09' => null,
'promotion_amount12' => null,
'promotion_amount18' => null,
'oxxo_pay' => null,
'active' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'store_id_adq' => 'storeIdAdq',
'private_key' => 'privateKey',
'status' => 'status',
'mid' => 'mid',
'organization_id' => 'organizationId',
'web_authorizer_url' => 'webAuthorizerUrl',
'merchant_web_hook' => 'merchantWebHook',
'created_date' => 'createdDate',
'updated_date' => 'updatedDate',
'cash_payment_enable' => 'cashPaymentEnable',
'day_payment_expire' => 'dayPaymentExpire',
'brand_card_allow' => 'brandCardAllow',
'promotion_enable' => 'promotionEnable',
'promotion_allow' => 'promotionAllow',
'credit_card_enable' => 'creditCardEnable',
'debit_card_enable' => 'debitCardEnable',
'image_header' => 'imageHeader',
'image_name' => 'imageName',
'color_header' => 'colorHeader',
'color_button' => 'colorButton',
'promotion_amount03' => 'promotionAmount03',
'promotion_amount06' => 'promotionAmount06',
'promotion_amount09' => 'promotionAmount09',
'promotion_amount12' => 'promotionAmount12',
'promotion_amount18' => 'promotionAmount18',
'oxxo_pay' => 'oxxoPay',
'active' => 'active'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'store_id_adq' => 'setStoreIdAdq',
'private_key' => 'setPrivateKey',
'status' => 'setStatus',
'mid' => 'setMid',
'organization_id' => 'setOrganizationId',
'web_authorizer_url' => 'setWebAuthorizerUrl',
'merchant_web_hook' => 'setMerchantWebHook',
'created_date' => 'setCreatedDate',
'updated_date' => 'setUpdatedDate',
'cash_payment_enable' => 'setCashPaymentEnable',
'day_payment_expire' => 'setDayPaymentExpire',
'brand_card_allow' => 'setBrandCardAllow',
'promotion_enable' => 'setPromotionEnable',
'promotion_allow' => 'setPromotionAllow',
'credit_card_enable' => 'setCreditCardEnable',
'debit_card_enable' => 'setDebitCardEnable',
'image_header' => 'setImageHeader',
'image_name' => 'setImageName',
'color_header' => 'setColorHeader',
'color_button' => 'setColorButton',
'promotion_amount03' => 'setPromotionAmount03',
'promotion_amount06' => 'setPromotionAmount06',
'promotion_amount09' => 'setPromotionAmount09',
'promotion_amount12' => 'setPromotionAmount12',
'promotion_amount18' => 'setPromotionAmount18',
'oxxo_pay' => 'setOxxoPay',
'active' => 'setActive'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'store_id_adq' => 'getStoreIdAdq',
'private_key' => 'getPrivateKey',
'status' => 'getStatus',
'mid' => 'getMid',
'organization_id' => 'getOrganizationId',
'web_authorizer_url' => 'getWebAuthorizerUrl',
'merchant_web_hook' => 'getMerchantWebHook',
'created_date' => 'getCreatedDate',
'updated_date' => 'getUpdatedDate',
'cash_payment_enable' => 'getCashPaymentEnable',
'day_payment_expire' => 'getDayPaymentExpire',
'brand_card_allow' => 'getBrandCardAllow',
'promotion_enable' => 'getPromotionEnable',
'promotion_allow' => 'getPromotionAllow',
'credit_card_enable' => 'getCreditCardEnable',
'debit_card_enable' => 'getDebitCardEnable',
'image_header' => 'getImageHeader',
'image_name' => 'getImageName',
'color_header' => 'getColorHeader',
'color_button' => 'getColorButton',
'promotion_amount03' => 'getPromotionAmount03',
'promotion_amount06' => 'getPromotionAmount06',
'promotion_amount09' => 'getPromotionAmount09',
'promotion_amount12' => 'getPromotionAmount12',
'promotion_amount18' => 'getPromotionAmount18',
'oxxo_pay' => 'getOxxoPay',
'active' => 'getActive'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['store_id_adq'] = isset($data['store_id_adq']) ? $data['store_id_adq'] : null;
        $this->container['private_key'] = isset($data['private_key']) ? $data['private_key'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['mid'] = isset($data['mid']) ? $data['mid'] : null;
        $this->container['organization_id'] = isset($data['organization_id']) ? $data['organization_id'] : null;
        $this->container['web_authorizer_url'] = isset($data['web_authorizer_url']) ? $data['web_authorizer_url'] : null;
        $this->container['merchant_web_hook'] = isset($data['merchant_web_hook']) ? $data['merchant_web_hook'] : null;
        $this->container['created_date'] = isset($data['created_date']) ? $data['created_date'] : null;
        $this->container['updated_date'] = isset($data['updated_date']) ? $data['updated_date'] : null;
        $this->container['cash_payment_enable'] = isset($data['cash_payment_enable']) ? $data['cash_payment_enable'] : null;
        $this->container['day_payment_expire'] = isset($data['day_payment_expire']) ? $data['day_payment_expire'] : null;
        $this->container['brand_card_allow'] = isset($data['brand_card_allow']) ? $data['brand_card_allow'] : null;
        $this->container['promotion_enable'] = isset($data['promotion_enable']) ? $data['promotion_enable'] : null;
        $this->container['promotion_allow'] = isset($data['promotion_allow']) ? $data['promotion_allow'] : null;
        $this->container['credit_card_enable'] = isset($data['credit_card_enable']) ? $data['credit_card_enable'] : null;
        $this->container['debit_card_enable'] = isset($data['debit_card_enable']) ? $data['debit_card_enable'] : null;
        $this->container['image_header'] = isset($data['image_header']) ? $data['image_header'] : null;
        $this->container['image_name'] = isset($data['image_name']) ? $data['image_name'] : null;
        $this->container['color_header'] = isset($data['color_header']) ? $data['color_header'] : null;
        $this->container['color_button'] = isset($data['color_button']) ? $data['color_button'] : null;
        $this->container['promotion_amount03'] = isset($data['promotion_amount03']) ? $data['promotion_amount03'] : null;
        $this->container['promotion_amount06'] = isset($data['promotion_amount06']) ? $data['promotion_amount06'] : null;
        $this->container['promotion_amount09'] = isset($data['promotion_amount09']) ? $data['promotion_amount09'] : null;
        $this->container['promotion_amount12'] = isset($data['promotion_amount12']) ? $data['promotion_amount12'] : null;
        $this->container['promotion_amount18'] = isset($data['promotion_amount18']) ? $data['promotion_amount18'] : null;
        $this->container['oxxo_pay'] = isset($data['oxxo_pay']) ? $data['oxxo_pay'] : null;
        $this->container['active'] = isset($data['active']) ? $data['active'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets store_id_adq
     *
     * @return int
     */
    public function getStoreIdAdq()
    {
        return $this->container['store_id_adq'];
    }

    /**
     * Sets store_id_adq
     *
     * @param int $store_id_adq store_id_adq
     *
     * @return $this
     */
    public function setStoreIdAdq($store_id_adq)
    {
        $this->container['store_id_adq'] = $store_id_adq;

        return $this;
    }

    /**
     * Gets private_key
     *
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->container['private_key'];
    }

    /**
     * Sets private_key
     *
     * @param string $private_key private_key
     *
     * @return $this
     */
    public function setPrivateKey($private_key)
    {
        $this->container['private_key'] = $private_key;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Netpay\Client\Model\ConfigResponseStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Netpay\Client\Model\ConfigResponseStatus $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets mid
     *
     * @return string
     */
    public function getMid()
    {
        return $this->container['mid'];
    }

    /**
     * Sets mid
     *
     * @param string $mid mid
     *
     * @return $this
     */
    public function setMid($mid)
    {
        $this->container['mid'] = $mid;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return string
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string $organization_id organization_id
     *
     * @return $this
     */
    public function setOrganizationId($organization_id)
    {
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets web_authorizer_url
     *
     * @return string
     */
    public function getWebAuthorizerUrl()
    {
        return $this->container['web_authorizer_url'];
    }

    /**
     * Sets web_authorizer_url
     *
     * @param string $web_authorizer_url web_authorizer_url
     *
     * @return $this
     */
    public function setWebAuthorizerUrl($web_authorizer_url)
    {
        $this->container['web_authorizer_url'] = $web_authorizer_url;

        return $this;
    }

    /**
     * Gets merchant_web_hook
     *
     * @return string
     */
    public function getMerchantWebHook()
    {
        return $this->container['merchant_web_hook'];
    }

    /**
     * Sets merchant_web_hook
     *
     * @param string $merchant_web_hook merchant_web_hook
     *
     * @return $this
     */
    public function setMerchantWebHook($merchant_web_hook)
    {
        $this->container['merchant_web_hook'] = $merchant_web_hook;

        return $this;
    }

    /**
     * Gets created_date
     *
     * @return string
     */
    public function getCreatedDate()
    {
        return $this->container['created_date'];
    }

    /**
     * Sets created_date
     *
     * @param string $created_date created_date
     *
     * @return $this
     */
    public function setCreatedDate($created_date)
    {
        $this->container['created_date'] = $created_date;

        return $this;
    }

    /**
     * Gets updated_date
     *
     * @return string
     */
    public function getUpdatedDate()
    {
        return $this->container['updated_date'];
    }

    /**
     * Sets updated_date
     *
     * @param string $updated_date updated_date
     *
     * @return $this
     */
    public function setUpdatedDate($updated_date)
    {
        $this->container['updated_date'] = $updated_date;

        return $this;
    }

    /**
     * Gets cash_payment_enable
     *
     * @return string
     */
    public function getCashPaymentEnable()
    {
        return $this->container['cash_payment_enable'];
    }

    /**
     * Sets cash_payment_enable
     *
     * @param string $cash_payment_enable cash_payment_enable
     *
     * @return $this
     */
    public function setCashPaymentEnable($cash_payment_enable)
    {
        $this->container['cash_payment_enable'] = $cash_payment_enable;

        return $this;
    }

    /**
     * Gets day_payment_expire
     *
     * @return int
     */
    public function getDayPaymentExpire()
    {
        return $this->container['day_payment_expire'];
    }

    /**
     * Sets day_payment_expire
     *
     * @param int $day_payment_expire day_payment_expire
     *
     * @return $this
     */
    public function setDayPaymentExpire($day_payment_expire)
    {
        $this->container['day_payment_expire'] = $day_payment_expire;

        return $this;
    }

    /**
     * Gets brand_card_allow
     *
     * @return string
     */
    public function getBrandCardAllow()
    {
        return $this->container['brand_card_allow'];
    }

    /**
     * Sets brand_card_allow
     *
     * @param string $brand_card_allow brand_card_allow
     *
     * @return $this
     */
    public function setBrandCardAllow($brand_card_allow)
    {
        $this->container['brand_card_allow'] = $brand_card_allow;

        return $this;
    }

    /**
     * Gets promotion_enable
     *
     * @return string
     */
    public function getPromotionEnable()
    {
        return $this->container['promotion_enable'];
    }

    /**
     * Sets promotion_enable
     *
     * @param string $promotion_enable promotion_enable
     *
     * @return $this
     */
    public function setPromotionEnable($promotion_enable)
    {
        $this->container['promotion_enable'] = $promotion_enable;

        return $this;
    }

    /**
     * Gets promotion_allow
     *
     * @return string
     */
    public function getPromotionAllow()
    {
        return $this->container['promotion_allow'];
    }

    /**
     * Sets promotion_allow
     *
     * @param string $promotion_allow promotion_allow
     *
     * @return $this
     */
    public function setPromotionAllow($promotion_allow)
    {
        $this->container['promotion_allow'] = $promotion_allow;

        return $this;
    }

    /**
     * Gets credit_card_enable
     *
     * @return string
     */
    public function getCreditCardEnable()
    {
        return $this->container['credit_card_enable'];
    }

    /**
     * Sets credit_card_enable
     *
     * @param string $credit_card_enable credit_card_enable
     *
     * @return $this
     */
    public function setCreditCardEnable($credit_card_enable)
    {
        $this->container['credit_card_enable'] = $credit_card_enable;

        return $this;
    }

    /**
     * Gets debit_card_enable
     *
     * @return string
     */
    public function getDebitCardEnable()
    {
        return $this->container['debit_card_enable'];
    }

    /**
     * Sets debit_card_enable
     *
     * @param string $debit_card_enable debit_card_enable
     *
     * @return $this
     */
    public function setDebitCardEnable($debit_card_enable)
    {
        $this->container['debit_card_enable'] = $debit_card_enable;

        return $this;
    }

    /**
     * Gets image_header
     *
     * @return string
     */
    public function getImageHeader()
    {
        return $this->container['image_header'];
    }

    /**
     * Sets image_header
     *
     * @param string $image_header image_header
     *
     * @return $this
     */
    public function setImageHeader($image_header)
    {
        $this->container['image_header'] = $image_header;

        return $this;
    }

    /**
     * Gets image_name
     *
     * @return string
     */
    public function getImageName()
    {
        return $this->container['image_name'];
    }

    /**
     * Sets image_name
     *
     * @param string $image_name image_name
     *
     * @return $this
     */
    public function setImageName($image_name)
    {
        $this->container['image_name'] = $image_name;

        return $this;
    }

    /**
     * Gets color_header
     *
     * @return string
     */
    public function getColorHeader()
    {
        return $this->container['color_header'];
    }

    /**
     * Sets color_header
     *
     * @param string $color_header color_header
     *
     * @return $this
     */
    public function setColorHeader($color_header)
    {
        $this->container['color_header'] = $color_header;

        return $this;
    }

    /**
     * Gets color_button
     *
     * @return string
     */
    public function getColorButton()
    {
        return $this->container['color_button'];
    }

    /**
     * Sets color_button
     *
     * @param string $color_button color_button
     *
     * @return $this
     */
    public function setColorButton($color_button)
    {
        $this->container['color_button'] = $color_button;

        return $this;
    }

    /**
     * Gets promotion_amount03
     *
     * @return string
     */
    public function getPromotionAmount03()
    {
        return $this->container['promotion_amount03'];
    }

    /**
     * Sets promotion_amount03
     *
     * @param string $promotion_amount03 promotion_amount03
     *
     * @return $this
     */
    public function setPromotionAmount03($promotion_amount03)
    {
        $this->container['promotion_amount03'] = $promotion_amount03;

        return $this;
    }

    /**
     * Gets promotion_amount06
     *
     * @return string
     */
    public function getPromotionAmount06()
    {
        return $this->container['promotion_amount06'];
    }

    /**
     * Sets promotion_amount06
     *
     * @param string $promotion_amount06 promotion_amount06
     *
     * @return $this
     */
    public function setPromotionAmount06($promotion_amount06)
    {
        $this->container['promotion_amount06'] = $promotion_amount06;

        return $this;
    }

    /**
     * Gets promotion_amount09
     *
     * @return string
     */
    public function getPromotionAmount09()
    {
        return $this->container['promotion_amount09'];
    }

    /**
     * Sets promotion_amount09
     *
     * @param string $promotion_amount09 promotion_amount09
     *
     * @return $this
     */
    public function setPromotionAmount09($promotion_amount09)
    {
        $this->container['promotion_amount09'] = $promotion_amount09;

        return $this;
    }

    /**
     * Gets promotion_amount12
     *
     * @return string
     */
    public function getPromotionAmount12()
    {
        return $this->container['promotion_amount12'];
    }

    /**
     * Sets promotion_amount12
     *
     * @param string $promotion_amount12 promotion_amount12
     *
     * @return $this
     */
    public function setPromotionAmount12($promotion_amount12)
    {
        $this->container['promotion_amount12'] = $promotion_amount12;

        return $this;
    }

    /**
     * Gets promotion_amount18
     *
     * @return string
     */
    public function getPromotionAmount18()
    {
        return $this->container['promotion_amount18'];
    }

    /**
     * Sets promotion_amount18
     *
     * @param string $promotion_amount18 promotion_amount18
     *
     * @return $this
     */
    public function setPromotionAmount18($promotion_amount18)
    {
        $this->container['promotion_amount18'] = $promotion_amount18;

        return $this;
    }

    /**
     * Gets oxxo_pay
     *
     * @return string
     */
    public function getOxxoPay()
    {
        return $this->container['oxxo_pay'];
    }

    /**
     * Sets oxxo_pay
     *
     * @param string $oxxo_pay oxxo_pay
     *
     * @return $this
     */
    public function setOxxoPay($oxxo_pay)
    {
        $this->container['oxxo_pay'] = $oxxo_pay;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool $active active
     *
     * @return $this
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)   
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
