<?php
/**
 * Ship
 *
 * PHP version 5
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Netpay API
 *
 * Netpay API for Cash and Credit Card
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Netpay\Client\Model;

use \ArrayAccess;
use \Netpay\Client\ObjectSerializer;

/**
 * Ship Class Doc Comment
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class oxxoPayConfig implements ModelInterface, ArrayAccess 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'oxxoPay';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ennable' => 'string',
        'type' => 'string',
        'paymentExpiration' => 'string',
        'paymentExpirationType' => 'string',
        'minAmount' => 'string',
        'maxAmount' => 'string'];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ennable' => null,
        'type' => null,
        'paymentExpiration' => null,
        'paymentExpirationType' => null,
        'minAmount' => null,
        'maxAmount' => null];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ennable' => 'ennable',
        'type' => 'type',
        'paymentExpiration' => 'paymentExpiration',
        'paymentExpirationType' => 'paymentExpirationType',
        'minAmount' => 'minAmount',
        'maxAmount' => 'maxAmount'];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ennable' => 'setEnable',
        'type' => 'setType',
        'paymentExpiration' => 'setPaymentExpiration',
        'paymentExpirationType' => 'setPaymentExpirationType',
        'minAmount' => 'setMinAmount',
        'maxAmount' => 'setMaxAmount'];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ennable' => 'getEnable',
        'type' => 'getType',
        'paymentExpiration' => 'getPaymentExpiration',
        'paymentExpirationType' => 'getPaymentExpirationType',
        'minAmount' => 'getMinAmount',
        'maxAmount' => 'getMaxAmount'];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

        /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['ennable'] = isset($data['ennable']) ? $data['ennable'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['paymentExpiration'] = isset($data['paymentExpiration']) ? $data['paymentExpiration'] : null;
        $this->container['paymentExpirationType'] = isset($data['paymentExpirationType']) ? $data['paymentExpirationType'] : null;
        $this->container['minAmount'] = isset($data['minAmount']) ? $data['minAmount'] : null;
        $this->container['maxAmount'] = isset($data['maxAmount']) ? $data['maxAmount'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets ennable
     *
     * @return string
     */
    public function getEnable()
    {
        return $this->container['ennable'];
    }

    /**
     * Sets ennable
     *
     * @param string $ennable ennable
     *
     * @return $this
     */
    public function setEnable($ennable)
    {
        $this->container['ennable'] = $ennable;

        return $this;
    }

        /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }


    /**
     * Gets paymentExpiration
     *
     * @return string
     */
    public function getPaymentExpiration()
    {
        return $this->container['paymentExpiration'];
    }

    /**
     * Sets paymentExpiration
     *
     * @param string $paymentExpiration paymentExpiration
     *
     * @return $this
     */
    public function setPaymentExpiration($paymentExpiration)
    {
        $this->container['paymentExpiration'] = $paymentExpiration;

        return $this;
    }

        /**
     * Gets paymentExpirationType
     *
     * @return string
     */
    public function getPaymentExpirationType()
    {
        return $this->container['paymentExpirationType'];
    }

    /**
     * Sets paymentExpirationType
     *
     * @param string $paymentExpirationType paymentExpirationType
     *
     * @return $this
     */
    public function setPaymentExpirationType($paymentExpirationType)
    {
        $this->container['paymentExpirationType'] = $paymentExpirationType;

        return $this;
    }

        /**
     * Gets minAmount
     *
     * @return string
     */
    public function getMinAmount()
    {
        return $this->container['minAmount'];
    }

    /**
     * Sets minAmount
     *
     * @param string $minAmount minAmount
     *
     * @return $this
     */
    public function setMinAmount($minAmount)
    {
        $this->container['minAmount'] = $minAmount;

        return $this;
    }

            /**
     * Gets maxAmount
     *
     * @return string
     */
    public function getMaxAmount()
    {
        return $this->container['maxAmount'];
    }

    /**
     * Sets maxAmount
     *
     * @param string $maxAmount maxAmount
     *
     * @return $this
     */
    public function setMaxAmount($maxAmount)
    {
        $this->container['maxAmount'] = $maxAmount;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
