<?php
/**
 * RefundResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Netpay API
 *
 * Netpay API for Cash and Credit Card
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Netpay\Client\Model;

use \ArrayAccess;
use \Netpay\Client\ObjectSerializer;

/**
 * RefundResponse Class Doc Comment
 *
 * @category Class
 * @package  Netpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RefundResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RefundResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'transaction_token_id' => 'string',
'status' => 'string',
'merchant_reference_code' => 'string',
'currency' => 'string',
'amount' => 'float',
'time_in' => 'string',
'time_out' => 'string',
'response_code' => 'string',
'response_msg' => 'string',
'auth_code' => 'string',
'span_route_number' => 'string',
'card_holder_name' => 'string',
'bill_to_email' => 'string',
'bank_name' => 'string',
'payment_method' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'transaction_token_id' => null,
'status' => null,
'merchant_reference_code' => null,
'currency' => null,
'amount' => 'float',
'time_in' => null,
'time_out' => null,
'response_code' => null,
'response_msg' => null,
'auth_code' => null,
'span_route_number' => null,
'card_holder_name' => null,
'bill_to_email' => null,
'bank_name' => null,
'payment_method' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transaction_token_id' => 'transactionTokenId',
'status' => 'status',
'merchant_reference_code' => 'merchantReferenceCode',
'currency' => 'currency',
'amount' => 'amount',
'time_in' => 'timeIn',
'time_out' => 'timeOut',
'response_code' => 'responseCode',
'response_msg' => 'responseMsg',
'auth_code' => 'authCode',
'span_route_number' => 'spanRouteNumber',
'card_holder_name' => 'cardHolderName',
'bill_to_email' => 'billToEmail',
'bank_name' => 'bankName',
'payment_method' => 'paymentMethod'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transaction_token_id' => 'setTransactionTokenId',
'status' => 'setStatus',
'merchant_reference_code' => 'setMerchantReferenceCode',
'currency' => 'setCurrency',
'amount' => 'setAmount',
'time_in' => 'setTimeIn',
'time_out' => 'setTimeOut',
'response_code' => 'setResponseCode',
'response_msg' => 'setResponseMsg',
'auth_code' => 'setAuthCode',
'span_route_number' => 'setSpanRouteNumber',
'card_holder_name' => 'setCardHolderName',
'bill_to_email' => 'setBillToEmail',
'bank_name' => 'setBankName',
'payment_method' => 'setPaymentMethod'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transaction_token_id' => 'getTransactionTokenId',
'status' => 'getStatus',
'merchant_reference_code' => 'getMerchantReferenceCode',
'currency' => 'getCurrency',
'amount' => 'getAmount',
'time_in' => 'getTimeIn',
'time_out' => 'getTimeOut',
'response_code' => 'getResponseCode',
'response_msg' => 'getResponseMsg',
'auth_code' => 'getAuthCode',
'span_route_number' => 'getSpanRouteNumber',
'card_holder_name' => 'getCardHolderName',
'bill_to_email' => 'getBillToEmail',
'bank_name' => 'getBankName',
'payment_method' => 'getPaymentMethod'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['transaction_token_id'] = isset($data['transaction_token_id']) ? $data['transaction_token_id'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['merchant_reference_code'] = isset($data['merchant_reference_code']) ? $data['merchant_reference_code'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['time_in'] = isset($data['time_in']) ? $data['time_in'] : null;
        $this->container['time_out'] = isset($data['time_out']) ? $data['time_out'] : null;
        $this->container['response_code'] = isset($data['response_code']) ? $data['response_code'] : null;
        $this->container['response_msg'] = isset($data['response_msg']) ? $data['response_msg'] : null;
        $this->container['auth_code'] = isset($data['auth_code']) ? $data['auth_code'] : null;
        $this->container['span_route_number'] = isset($data['span_route_number']) ? $data['span_route_number'] : null;
        $this->container['card_holder_name'] = isset($data['card_holder_name']) ? $data['card_holder_name'] : null;
        $this->container['bill_to_email'] = isset($data['bill_to_email']) ? $data['bill_to_email'] : null;
        $this->container['bank_name'] = isset($data['bank_name']) ? $data['bank_name'] : null;
        $this->container['payment_method'] = isset($data['payment_method']) ? $data['payment_method'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transaction_token_id
     *
     * @return string
     */
    public function getTransactionTokenId()
    {
        return $this->container['transaction_token_id'];
    }

    /**
     * Sets transaction_token_id
     *
     * @param string $transaction_token_id transaction_token_id
     *
     * @return $this
     */
    public function setTransactionTokenId($transaction_token_id)
    {
        $this->container['transaction_token_id'] = $transaction_token_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets merchant_reference_code
     *
     * @return string
     */
    public function getMerchantReferenceCode()
    {
        return $this->container['merchant_reference_code'];
    }

    /**
     * Sets merchant_reference_code
     *
     * @param string $merchant_reference_code merchant_reference_code
     *
     * @return $this
     */
    public function setMerchantReferenceCode($merchant_reference_code)
    {
        $this->container['merchant_reference_code'] = $merchant_reference_code;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency currency
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float $amount amount
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets time_in
     *
     * @return string
     */
    public function getTimeIn()
    {
        return $this->container['time_in'];
    }

    /**
     * Sets time_in
     *
     * @param string $time_in time_in
     *
     * @return $this
     */
    public function setTimeIn($time_in)
    {
        $this->container['time_in'] = $time_in;

        return $this;
    }

    /**
     * Gets time_out
     *
     * @return string
     */
    public function getTimeOut()
    {
        return $this->container['time_out'];
    }

    /**
     * Sets time_out
     *
     * @param string $time_out time_out
     *
     * @return $this
     */
    public function setTimeOut($time_out)
    {
        $this->container['time_out'] = $time_out;

        return $this;
    }

    /**
     * Gets response_code
     *
     * @return string
     */
    public function getResponseCode()
    {
        return $this->container['response_code'];
    }

    /**
     * Sets response_code
     *
     * @param string $response_code response_code
     *
     * @return $this
     */
    public function setResponseCode($response_code)
    {
        $this->container['response_code'] = $response_code;

        return $this;
    }

    /**
     * Gets response_msg
     *
     * @return string
     */
    public function getResponseMsg()
    {
        return $this->container['response_msg'];
    }

    /**
     * Sets response_msg
     *
     * @param string $response_msg response_msg
     *
     * @return $this
     */
    public function setResponseMsg($response_msg)
    {
        $this->container['response_msg'] = $response_msg;

        return $this;
    }

    /**
     * Gets auth_code
     *
     * @return string
     */
    public function getAuthCode()
    {
        return $this->container['auth_code'];
    }

    /**
     * Sets auth_code
     *
     * @param string $auth_code auth_code
     *
     * @return $this
     */
    public function setAuthCode($auth_code)
    {
        $this->container['auth_code'] = $auth_code;

        return $this;
    }

    /**
     * Gets span_route_number
     *
     * @return string
     */
    public function getSpanRouteNumber()
    {
        return $this->container['span_route_number'];
    }

    /**
     * Sets span_route_number
     *
     * @param string $span_route_number span_route_number
     *
     * @return $this
     */
    public function setSpanRouteNumber($span_route_number)
    {
        $this->container['span_route_number'] = $span_route_number;

        return $this;
    }

    /**
     * Gets card_holder_name
     *
     * @return string
     */
    public function getCardHolderName()
    {
        return $this->container['card_holder_name'];
    }

    /**
     * Sets card_holder_name
     *
     * @param string $card_holder_name card_holder_name
     *
     * @return $this
     */
    public function setCardHolderName($card_holder_name)
    {
        $this->container['card_holder_name'] = $card_holder_name;

        return $this;
    }

    /**
     * Gets bill_to_email
     *
     * @return string
     */
    public function getBillToEmail()
    {
        return $this->container['bill_to_email'];
    }

    /**
     * Sets bill_to_email
     *
     * @param string $bill_to_email bill_to_email
     *
     * @return $this
     */
    public function setBillToEmail($bill_to_email)
    {
        $this->container['bill_to_email'] = $bill_to_email;

        return $this;
    }

    /**
     * Gets bank_name
     *
     * @return string
     */
    public function getBankName()
    {
        return $this->container['bank_name'];
    }

    /**
     * Sets bank_name
     *
     * @param string $bank_name bank_name
     *
     * @return $this
     */
    public function setBankName($bank_name)
    {
        $this->container['bank_name'] = $bank_name;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return string
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param string $payment_method payment_method
     *
     * @return $this
     */
    public function setPaymentMethod($payment_method)
    {
        $this->container['payment_method'] = $payment_method;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
