[Shop]
name = Magento
version = 2

[HOST]
apiurltest = https://gateway-154.netpaydev.com/gateway-ecommerce/
apiurllive = https://suite.netpay.com.mx/gateway-ecommerce/
useKeysFromConfig = true

[DebugFile]
; path = /Applications/MAMP/logs/netpay.log

[Authentification]
type = Signature
passwordtest = secret_key_test
passwordlive = secret_key_live
keytest = public_key_test
keylive = public_key_live
mode = mode
useKeysFromConfig = false

[Tokenisation]
apiClass = \Netpay\Client\Api\OrdersApi
requestModel = \Netpay\Client\Model\Charges
method = chargesPost

[GetOrder]
apiClass = \Netpay\Client\Api\OrdersApi
method = transactionsTransactionTokenGet

[Confirm]
apiClass = \Netpay\Client\Api\OrdersApi
method = transactionTokenConfirmPost

[Refund]
apiClass = \Netpay\Client\Api\OrdersApi
method = transactionsTransactionTokenidRefundPost

[GetStores]
apiClass = \Netpay\Client\Api\OrdersApi
method = storesGet

[GetWebhook]
apiClass = \Netpay\Client\Api\WebhooksApi
method = webhooksGet

[SetWebhook]
apiClass = \Netpay\Client\Api\WebhooksApi
requestModel = \Netpay\Client\Model\Hook
method = webhooksPost

[UpdateWebhook]
apiClass = \Netpay\Client\Api\WebhooksApi
requestModel = \Netpay\Client\Model\Hook
method = webhooksPut

[GetClient]
apiClass = \Netpay\Client\Api\ClientsApi
method = clientsClientIdGet

[SetClient]
apiClass = \Netpay\Client\Api\ClientsApi
requestModel = \Netpay\Client\Model\CreateClientRequest
method = clientsPost

[UpdateClient]
apiClass = \Netpay\Client\Api\ClientsApi
requestModel = \Netpay\Client\Model\Token
method = clientsClientIdTokenPut

[DeleteClient]
apiClass = \Netpay\Client\Api\ClientsApi
method = clientsClientIdTokenTransactionTokenDelete

[Configuration]
apiClass = \Netpay\Client\Api\WebhooksApi
method = configGet

[UsedFeatures]
Features[] = configuration
Features[] = tokenisation
Features[] = getorder
Features[] = confirm
Features[] = widget
Features[] = redirect
Features[] = refund
Features[] = getstores
Features[] = getwebhook
Features[] = setwebhook
Features[] = updatewebhook
Features[] = getclient
Features[] = setclient
Features[] = updateclient
Features[] = deleteclient

[ThirdPartyFiles]
thirdpartyScript = https://docs.netpay.mx/cdn/v1.3/netpay.min.js

[PlugIntFilesFolderPath]
url = vendor/ideatarmac/netpay/businessLayer/Features/PaymentPage/files